name: CI/CD Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/nanet-portfolio:latest
          docker build \
            --secret id=PAYLOAD_SECRET,env=PAYLOAD_SECRET \
            --secret id=DATABASE_URL,env=DATABASE_URL \
            --secret id=CRON_SECRET,env=CRON_SECRET \
            --secret id=PREVIEW_SECRET,env=PREVIEW_SECRET \
            -t $IMAGE_NAME .
          docker push $IMAGE_NAME
        env:
          PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_PUBLIC_SERVER_URL: ${{ secrets.NEXT_PUBLIC_SERVER_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          PREVIEW_SECRET: ${{ secrets.PREVIEW_SECRET }}
      - name: Prepare remote directory
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: 2222
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir -p /home/dev/nanet-portfolio
      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: 2222
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: docker-compose.yml
          target: /home/dev/nanet-portfolio
      - name: Deploy via Docker Compose
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: 2222
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/dev/nanet-portfolio
            # --- create temporary .env file with secrets ---
            cat > .env <<EOF
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            PAYLOAD_SECRET=${{ secrets.PAYLOAD_SECRET }}
            CRON_SECRET=${{ secrets.CRON_SECRET }}
            NEXT_PUBLIC_SERVER_URL=${{ secrets.NEXT_PUBLIC_SERVER_URL }}
            PREVIEW_SECRET=${{ secrets.PREVIEW_SECRET }}
            EOF
            # --- run Docker Compose with .env file ---          
            docker-compose pull
            docker-compose up -d --remove-orphans
            docker system prune -f
